name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: ["master"]

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-git-committers-plugin-2
          pip install mkdocs-git-revision-date-localized-plugin

      - name: Configure Git for GitHub Actions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build MkDocs site
        env:
          MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdocs build

      - name: Deploy to GitHub Pages using GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdocs gh-deploy --force --remote-branch gh-pages

